server:
  port: 7003

spring:
  application:
    name: eureka7003.com
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7004.com:7004/eureka/