server:
  port: 8001


spring:
  application:
    name: spring-cloud-payment

  datasource:
    password: Bb@136320
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  org.gjt.mm.mysql.Driver
    url: jdbc:mysql://1.15.80.96:3306/lizhi?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC

mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  instance:
    prefer-ip-address: true
    hostname: payment8001
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7004.com:7004/eureka/
