server:
  port: 8002

spring:
  application:
    name: spring-cloud-payment
  datasource:
    url: jdbc:mysql://1.15.80.96:3306/lizhi?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    password: Bb@136320
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  instance:
    hostname: payment8002
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7004.com:7004/eureka/
